### ISSUE TITLE
Replace mousePressed function with gui control

### ISSUE THREAD

**Issue by CCruzG** [GenArtRepo/flocking#1]
We could replace the mousePress interaction with a slider control in the gui, to change the number of boids.
 
https://github.com/GenArtRepo/flocking/blob/d3e99934f5aaf14acbf25b45fdcf5ae1b752eb13/sketch.js#L68-L72

**Comment by crarojasca** [comment]
Hi Camilo, I just linked the pull request that solves this issue as you see above, now you can check the pull request and accept it or add more changes that could be required. If you accept the pull request you can close the issue after that.
